---
title: "Learning to reference figures,tables and sections"
author: "Rachel Xu"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2
keep_md: yes
---

```{r global, include = FALSE}
knitr::opts_chunk$set(fig.align= "center") # give you global options this line of function
```

```{r, message = FALSE}
library(tidyverse)
```

# Learning to reference figures {#figures}

```{r FigRef, fig.cap= "This is a line plot"} 
# FigRef will be used as a reference for the Figure, the figure will also need to have a caption.
#{figures are used for sections reference at the end}
x = seq(1:100) #
y = rnorm(100) #
dat = data.frame(x, y)
ggplot(dat, aes(x = x, y = y)) +
geom_line()
```

In Figure  \@ref(fig:FigRef), we. have plot x versus y.

# Learning to reference tables {#tables}

In table \@ref(tab:TableRef), we have shown the first five rows of the data.
```{r TableRef}
head(dat, n=5) %>% 
  knitr::kable(caption = "First five rows of the data.")
# to print a table, we will use kable function from knitr package, and the caption is used using kable function
```



# Learning to reference sections 

In Section \@ref(figures), we plot a figure. While in Section \@ref(tables), we produced a table.

```{r}

```


